### ISSUE TITLE
Text field displayed as floating point

### ISSUE THREAD

**Issue by mquinnv** [dbcli/pgcli#280]
![data](https://cloud.githubusercontent.com/assets/932611/8684632/977a6f8a-2a47-11e5-8682-eb79a7f6bf9f.png)
![table-def](https://cloud.githubusercontent.com/assets/932611/8684633/9786c488-2a47-11e5-9970-821f24f1b257.png)

**Comment by mquinnv** [comment]
pls let me know if i'm missing something obvious. the data happens to look like a floating point number, but it isn't.

**Comment by amjith** [comment]
The tabulate library used by pgcli tries to be clever and attempts to auto-detect the data types. Which is why it recognized the column as float. 

Unfortunately I don't have an easy solution for that right now. I'll try and use a different library in the future. 

Sorry about that.

**Comment by mquinnv** [comment]
np, glad i'm not insane. great job tho. kicks psql's butt

**Comment by amjith** [comment]
This is fixed in the latest version of pgcli (v1.0.1). 

Please upgrade: 


```
```

**Comment by mquinnv** [comment]
i'm a little confused by the versioning. latest release is showing as 1.2, and is what i get if i upgrade via pip. but you mentioned 1.0.1. the bug is still present in 1.2. am i being dumb?

**Comment by amjith** [comment]
Sorry the bug is not yet fixed. I fixed a related bug in 0.16.0 and I thought I addressed this issue. But looks like I misspoke. 😞

**Comment by amjith** [comment]
Also I should not have said 1.0.1. I don't think that version even exists. 😞

**Comment by amjith** [comment]
This is now fixed in the latest version.
